### PR TITLE
Test run of CI1

### PR DESCRIPTION
**Pull request by nkprince007**

### CODE REVIEW

**Comment by nkprince007** [comment]
@gitmate-bot coafile please.

**Comment by coafile** [comment]
Greetings! I am the coafile bot. Sit Tight! I will get your coafile ready.

**Comment by coafile** [comment]
Here's your coafile: :tada:

```# Generated by coala-quickstart on 02 Dec 2017.
[default]
bears = LineCountBear, InvalidLinkBear, FilenameBear
files = **.html, **.json, **.pm, **.h, **.glade, **.css, **.rest, **.rst, **.py, **.tex, **.pl, **.cpp, **.svg, **.c, **.md, **.mm
[xml]
bears = XMLBear, coalaBear, LineLengthBear, SpaceConsistencyBear, DuplicateFileBear, KeywordBear, LicenseCheckBear
files = **.glade, **.svg
[html]
bears = BootLintBear, coalaBear, LineLengthBear, HTMLLintBear, SpaceConsistencyBear, DuplicateFileBear, KeywordBear, LicenseCheckBear
files = **.html
[restructuredtext]
bears = RSTcheckBear, reSTLintBear, coalaBear, LineLengthBear, SpaceConsistencyBear, DuplicateFileBear, KeywordBear, LicenseCheckBear
files = **.rst, **.rest
[python]
bears = PycodestyleBear
files = **.py
[tex]
bears = KeywordBear, coalaBear, LineLengthBear, SpaceConsistencyBear, DuplicateFileBear, LatexLintBear, LicenseCheckBear
files = **.tex
[perl]
bears = coalaBear, LineLengthBear, SpaceConsistencyBear, DuplicateFileBear, PerlCriticBear, KeywordBear, LicenseCheckBear
files = **.pl, **.pm
[markdown]
bears = coalaBear, LineLengthBear, SpaceConsistencyBear, MarkdownBear, DuplicateFileBear, KeywordBear, LicenseCheckBear
files = **.md
[c]
bears = CSecurityBear, GNUIndentBear, ClangComplexityBear
files = **.h, **.c
[css]
bears = SpaceConsistencyBear, CSSLintBear
files = **.css
[c++]
bears = CPPCheckBear, ClangComplexityBear, GNUIndentBear, CPDBear, CPPCleanBear
files = **.cpp, **.h
[objective-c]
bears = ClangCloneDetectionBear, ClangComplexityBear, ClangASTPrintBear, LineLengthBear, SpaceConsistencyBear, coalaBear, ClangBear, DuplicateFileBear, CPDBear, ClangFunctionDifferenceBear, KeywordBear, LicenseCheckBear
files = **.mm
[json]
bears = coalaBear, LineLengthBear, SpaceConsistencyBear, DuplicateFileBear, JSONFormatBear, KeywordBear, LicenseCheckBear
files = **.json
```

**Comment by coafile** [comment]
Sorry! coafile is unable to make the PR.

**Comment by nkprince007** [comment]
@coafile try once more.

**Comment by coafile** [comment]
Greetings! I am the coafile bot. Sit Tight! I will get your coafile ready.

**Comment by coafile** [comment]
Here's your coafile: :tada:

```# Generated by coala-quickstart on 02 Dec 2017.
[default]
bears = InvalidLinkBear, LineCountBear, FilenameBear
files = **.rst, **.pm, **.css, **.mm, **.md, **.pl, **.py, **.tex, **.h, **.cpp, **.glade, **.svg, **.rest, **.html, **.json, **.c
[xml]
bears = LineLengthBear, SpaceConsistencyBear, coalaBear, DuplicateFileBear, LicenseCheckBear, KeywordBear, XMLBear
files = **.svg, **.glade
[html]
bears = BootLintBear, LineLengthBear, SpaceConsistencyBear, coalaBear, DuplicateFileBear, LicenseCheckBear, KeywordBear, HTMLLintBear
files = **.html
[restructuredtext]
bears = LineLengthBear, SpaceConsistencyBear, coalaBear, DuplicateFileBear, RSTcheckBear, LicenseCheckBear, KeywordBear, reSTLintBear
files = **.rest, **.rst
[python]
bears = PycodestyleBear
files = **.py
[tex]
bears = LatexLintBear, LineLengthBear, SpaceConsistencyBear, coalaBear, DuplicateFileBear, LicenseCheckBear, KeywordBear
files = **.tex
[perl]
bears = PerlCriticBear, LineLengthBear, SpaceConsistencyBear, coalaBear, DuplicateFileBear, LicenseCheckBear, KeywordBear
files = **.pl, **.pm
[markdown]
bears = LineLengthBear, SpaceConsistencyBear, coalaBear, DuplicateFileBear, LicenseCheckBear, KeywordBear, MarkdownBear
files = **.md
[c]
bears = GNUIndentBear, ClangComplexityBear, CSecurityBear
files = **.h, **.c
[css]
bears = SpaceConsistencyBear, CSSLintBear
files = **.css
[c++]
bears = CPPCheckBear, ClangComplexityBear, GNUIndentBear, CPPCleanBear, CPDBear
files = **.cpp, **.h
[objective-c]
bears = ClangASTPrintBear, ClangCloneDetectionBear, LineLengthBear, SpaceConsistencyBear, coalaBear, ClangComplexityBear, DuplicateFileBear, ClangBear, LicenseCheckBear, KeywordBear, CPDBear, ClangFunctionDifferenceBear
files = **.mm
[json]
bears = JSONFormatBear, LineLengthBear, SpaceConsistencyBear, coalaBear, DuplicateFileBear, LicenseCheckBear, KeywordBear
files = **.json
```

**Comment by coafile** [comment]
Successfully created the coafile pull request! :tada: 


Further Steps: 

- Merge the Pull Request https://api.github.com/repos/nkprince007/linux/issues/2 with the .coafile
- Turn on [GitMate](https://gitmate.io) Integration for this repository.
- Turn on code analysis for automated code reviews on all your pull requests.

Happy Linting! :tada:

**Pull request closed without merging**
